### ISSUE TITLE
Measure SMPL body

### ISSUE THREAD

**Issue by ByronLaw1025** [mbotsch/GarmentMeasurements#3]
I generate some SMPL body model for measurement, but it reture the error.
`(base) xxx@xxxMBP build % ./measurements smpl_A_00.obj A.yml`
`zsh: segmentation fault  ./measurements smpl_A_00.obj A.yml`

**Comment by mbotsch** [comment]
I'm sorry, but our code expects meshes with our template triangulation, not with that of SMPL.
